import blockContent from './blockContent'
import blockdocument from './blockdocument'
import post from './post'
import skill from './skill'
import accomplishment from './accomplishment'
import social from './social'
import company from './company'
import role from './role'
import tags from './tag'
import journalEnty from './journalEnty'
import readItem from './readItem'
import stickyNote from './stickyNote'
import board from './board'

export const schemaTypes = [social, accomplishment, skill, blockContent, blockdocument, company, role, tags, journalEnty, readItem, stickyNote,board]
